Development Final Code for Review
paulfrancis556/CMP1903_A1_2324 pull request #1
Opened 2024-03-05 00:39 UTC by paulfrancis556

2024-03-05 11:17 UTC, Stampyswamp requested changes
Super Code.

2024-03-05 11:17 UTC, Stampyswamp commented on CMP1903_A1_2324/Die.cs
+Correctly Laid Out
+Naming Convention follows brief
+Enough Comments to understand what is going on.

-Possibly (overkill) add a /// comment ontop of the function which explains what the function does.
#SUPER

2024-03-05 11:17 UTC, Stampyswamp commented on CMP1903_A1_2324/Game.cs
+Plenty Of Comments
+All names are fitting (dice and die is a bit confusing but its understandable why these are the names)
+Code is efficient and Effective by using minimal lines.
#SUPER

2024-03-05 11:17 UTC, Stampyswamp commented on CMP1903_A1_2324/Program.cs
+Nice and simple. No need for comment as you can easily understand what is happening.
-You could push this further and add an input system with defensive programming/ exception handling to be able to roll the dice more than one time, as per the briefs instructions.

2024-03-05 11:17 UTC, Stampyswamp commented on CMP1903_A1_2324/Testing.cs
+Fast and efficient.
+Plenty of Comments
-Again like before (Overkill) could use a /// style comment above the function to give a further summary
#SUPER

2024-03-05 11:17 UTC, Stampyswamp commented on CMP1903_A1_2324/Die.cs
if you need help with writing a /// I would recommend the following:
https://learn.microsoft.com/en-us/visualstudio/ide/reference/generate-xml-documentation-comments?view=vs-2022

2024-03-05 11:17 UTC, Stampyswamp commented on CMP1903_A1_2324/Game.cs
-Possibly explain the encapsulation with comments.

2024-03-05 11:17 UTC, Stampyswamp commented on CMP1903_A1_2324/Program.cs
-If you do expand with a quick input system comments would be advised.

2024-03-05 11:17 UTC, Stampyswamp commented on CMP1903_A1_2324/Testing.cs
>  }
Overall, Your code is very well thought out and written. this code is Ideal as it is compact and efficient. The code fits the brief as requested (-input system) and your code will report each roll individually which is an advanced functionality.

The use of comments are excellent as it makes the code very easy to read through and understand everything even while skimming through the text.

#All in All, Well Done. 😁

2024-03-05 11:19 UTC, Stampyswamp commented on CMP1903_A1_2324/Testing.cs
>  }
EXTRA- exception handling has been dealt with as there are currently no errors to arise.

2024-03-05 14:29 UTC, ML-04 commented on CMP1903_A1_2324/Game.cs
**Positive**
+ Not only do the comments provide a good explanation but there are many of them to provide what everything does.
+ The code is clear and concise.
+ The loop for is easy to understand.

**Negative**
- Provide a comment on the encapsulation method used.

2024-03-05 14:29 UTC, ML-04 commented on CMP1903_A1_2324/Program.cs
**Positive**
+ The code is clear and concise.

**Negative**
- Provide a comment explaining what this does.
- Expand on the current code to allow a user to roll the dice multiple times.

2024-03-05 14:29 UTC, ML-04 commented on CMP1903_A1_2324/Testing.cs
**Positive**
+ The code is clear and concise.
+ Each piece of code is explained well with a comment.

2024-03-06 23:08 UTC, paulfrancis556 reviewed
Changes complete
XML comments added

2024-03-06 23:08 UTC, merged